### ISSUE TITLE
Support using Spark with Fluo

### ISSUE THREAD

**Issue by mikewalch** [apache/incubator-fluo#403]
Currently, Fluo has only been demonstrated to work with MapReduce.  It would be nice if an example application was created showing how to use Fluo with Spark.

**Comment by cjnolet** [comment]
I may be able to help out with this one very soon. I've been using Spark for about 5 months now @ my day job. perhaps it's an opportunity for me to dive back into Fluo.

**Comment by mikewalch** [comment]
@cjnolet, that would be awesome!

**Comment by mikewalch** [comment]
This was addressed with [1.0.0-beta-2 release](https://fluo.apache.org/release-notes/1.0.0-beta-2/).
