### ISSUE TITLE
analyze dependencies

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#435]
Analyze fluo-core dependencies to determine if any could be made optional or removed.

**Comment by Garvit244** [comment]
What need to be done in this task ?

**Comment by joshelser** [comment]
It sounds like @keith-turner's original point might have been more targeted to reducing the scope of dependencies, but it would also be prudent to take a look through all of the dependencies to ensure that they are compatible with the Apache Software License.

See the following pages on [disallowed licenses](http://www.apache.org/legal/resolved.html#category-x) and [licenses whose code may only be redistributed in binary form](http://www.apache.org/legal/resolved.html#category-b) for the ASF licensing requirements.

**Comment by keith-turner** [comment]
@Garvit244 What I was thinking for this task was to run `mvn dependency:analyze` look at the output for each module and determine if dependencies need to be added or removed from the poms. As for the comment about optional, I am not sure exactly what I was thinking about there.

@joshelser I think what you suggested may be covered by #690?

**Comment by Garvit244** [comment]
I ran` mvn dependency:analyze` to check unused dependencies in modules pom. There are some of the dependencies which are used but undeclared
```
Used undeclared dependencies found:
 org.apache.hadoop:hadoop-common:jar:2.6.3:compile
Unused declared dependencies found:
 org.apache.hadoop:hadoop-client:jar:2.6.3:compile
```
Is these `org.apache.hadoop:hadoop-common` dependency is subpart of `org.apache.hadoop:hadoop-client`

**Comment by mikewalch** [comment]
Yes, hadoop-common is a dependency of hadoop-client.  We can rely on hadoop-client to bring in this dependency so it doesn't need to be included on its own in our pom. If you run `mvn dependency:tree`, you can verify this and see where other dependencies are coming from:
```
[INFO] +- org.apache.hadoop:hadoop-client:jar:2.6.3:compile
[INFO] |  +- org.apache.hadoop:hadoop-common:jar:2.6.3:compile
```

**Comment by keith-turner** [comment]
Hadoop client is a virtual (probably not the correct word) dependency that was created to make using hadoop eaiser.  I don't think it has any code associated with it.  I think it just points to all of the other hadoop client libs. 

Since it has no code, mvn dependency analysis thinks we are not using it.   However I think using hadoop client is the correct thing to do.  Using hadoop client will correctly set the version of hadoop common.

https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/2.7.2/hadoop-client-2.7.2.pom

**Comment by ctubbsii** [comment]
Yeah, this is one of those unusual scenarios where the best practice isn't the right thing to do. Best practice says we'd exclude the unused client, and include the used common jar explicitly. Unfortunately, the way Hadoop packages its artifacts, it makes stronger guarantees about the client jar (as a virtual/meta-dependency) and what classes/packages will be included (either directly, or transitively) than it does about the common jar.

So, for Hadoop, at least, the right thing to do is to depend on the client jar and not common.

**Comment by Garvit244** [comment]
Point Taken. Will keep client as dependencies in pom

**Comment by joshelser** [comment]
> @joshelser I think what you suggested may be covered by #690?

In part. The other half is a double-check that all dependencies are compatibly licensed with the ASLv2. I assume that was already the case (as fluo was already licensed as ASLv2), but it would be prudent to double check now that we're at the ASF.
