### ISSUE TITLE
Fluo exec command prints a message

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#629]
Fluo exec prints a message like the following when executing user code... probably should not.

```
Connecting to Fluo instance (localhost/fluo) using config (apps/myApp/conf/fluo.properties)
```

**Comment by mikewalch** [comment]
This was fixed in PR #687 - See this line in the [commit](https://github.com/apache/incubator-fluo/commit/6fd86298c7d6c4759df98e9d6633fe91ec036f99?diff=split#diff-342e5554e01b6078b1ac5c74f973f5d4L105)
