### ISSUE TITLE
Update pom to do Apache relase

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#688]
Now that Fluo has moved to Apache we need to update the pom to support creating an Apache release.

**Comment by Garvit244** [comment]
what needed to be done in this? Maven airtifact publishing need to be done in this issue
http://www.apache.org/dev/publishing-maven-artifacts.html

**Comment by ctubbsii** [comment]
Essentially, we need to switch from the fluo parent POM to the ASF parent POM, which serve similar purposes. There may be things in the fluo parent POM which are not in the ASF parent POM. In those cases, we need to reconcile the differences, either by dropping them, pushing them down into the individual project POMs, or by turning the current fluo parent POM into an intermediate POM, whose parent is the ASF parent POM (which I think is probably the best route).

**Comment by keith-turner** [comment]
I like the path of making the [current parent pom](https://github.com/fluo-io/resources/blob/613cf66b7894e9f376b6263a4a6ced8326e3e8dc/pom.xml) have Apache as a parent and reconciling the differences.

**Comment by keith-turner** [comment]
@Garvit244 responding to your email for more info here on the issue.  I am not sure exactly what needs to be done, but I will try to explain what I think needs to be done.  I may be wrong about some things.

Some quick background.  The [Fluo project pom][2] provides common functionality across Fluo project poms ([Fluo pom][3] and [Recipes pom][4]).  For example the Fluo parent pom sets up code formatting, findbugs, etc.  Therefore each project pom does not have to duplicate all of this.  The projects poms [used to duplicate][5] all of this before creating the Fluo project pom.

Now that we are moving to Apache we want to use config from the [Apache pom][1] to do releases.   We also want to keep things from the  [Fluo Project pom][2] like code formatting.  To accomplish this we can add the Apache as a parent of the Fluo project pom.

Also we need to remove the current info about releasing to Sonatype (where io.flou releases were done) from any of the poms where it may occur.

The following is the high level overview of what I think needs to be done.

 1. Add [Apache pom][1] as parent of [Fluo project pom][2]
 2. Reconcile plugin config that occur in both poms.  Feel free to ask about reconciling any duplicate plugins with different config.
 3. Remove Sonatype distribution management section from Fluo project pom.  Look for other Sonatye stuff to remove. (should inherit distribution management from Apache parent pom)
 4. Release new version of Fluo project pom
 5. Update [Fluo pom][3] and [Recipes pom][4] to use new version of Fluo project pom.
 
We were planning on releasing the Fluo project pom to Sonatype because we have not transitioned that project to Apache yet.   @ctubbsii  how can the Fluo project pom release to Sonatype if it drops Sonatype distribution management and inherits Apache distribution management?

[1]: https://repo1.maven.org/maven2/org/apache/apache/18/apache-18.pom
[2]: https://github.com/fluo-io/resources/blob/613cf66b7894e9f376b6263a4a6ced8326e3e8dc/pom.xml
[3]: https://github.com/apache/incubator-fluo/blob/fee0ca74d04aad8d0dc599817ac5deca19f92c44/pom.xml
[4]: https://github.com/apache/incubator-fluo-recipes/blob/93f482aa447e5f63c3e3406f05e328404ac143ba/pom.xml
[5]: https://github.com/apache/incubator-fluo/commit/2911b373357ee87c99e019475f3ade13c499205b#diff-600376dffeb79835ede4a0b285078036

**Comment by keith-turner** [comment]
An alternative to modifiying the existing  [Fluo project pom][1] is to create a new parent for Fluo and Fluo Recipes.  This could be stored in a branch of Fluo.   Then we would have a graph like the following.  This idea was suggested by @ctubbsii yesterday offline and I just remembered it.

 * FluoProjectParent has a parent of Apache pom
 * Fluo has a parent of FluoProjectParent
 * Fluo Recipes has a parent of FluoProjectParent

FluoProjectParent would be brand new and would have code formatting, findbugs, etc.   FluoProjectParent would be stored in a branch of the Fluo project that only has the pom.

**Comment by Garvit244** [comment]
@keith-turner Second approach looks good to me by that I didn't need to do any changes in current Fluo project pom. When new FluoProjectParent is done we only need to change Fluo project pom until then we can use current [Fluo project pom](https://github.com/fluo-io/resources/blob/613cf66b7894e9f376b6263a4a6ced8326e3e8dc/pom.xml)

**Comment by Garvit244** [comment]
I dont have access to create new repo in [Fluo-io](https://github.com/fluo-io). Can somebody create it then I will add all common resources ther.

**Comment by Garvit244** [comment]
Few questions:
Q1:  There are some of the resources which are in Apache Parent Pom but there configurations are different from what we use. For example:
Main Flo-parent-pom:
<plugin>
        <groupId>org.apache.rat</groupId>
        <artifactId>apache-rat-plugin</artifactId>
        <executions>
          <execution>
            <id>check-licenses</id>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

In apache parent Pom:
<plugin>
<groupId>org.apache.rat</groupId>
<artifactId>apache-rat-plugin</artifactId>
<version>0.11</version>
<configuration>

<excludes>
<exclude>DEPENDENCIES</exclude>
</excludes>
</configuration>
<dependencies>

<dependency>
<groupId>org.apache.maven.doxia</groupId>
<artifactId>doxia-core</artifactId>
<version>1.2</version>
<exclusions>
<exclusion>

<groupId>xerces</groupId>
<artifactId>xercesImpl</artifactId>
</exclusion>
</exclusions>
</dependency>
</dependencies>
</plugin>

**Comment by ctubbsii** [comment]
@Garvit244 I'll create a separate branch called "fluo-parent" for you to do a pull request against. In that pull request, you can point its parent to the Apache parent, and rename this pom to "fluo-parent", as well as reconcile the redundant areas.

You can then do a second pull request against the "master" branch to rename it's root pom's artifactId from "fluo-parent" to just simply "fluo", and point its parent to the new "fluo-parent" which is in the "fluo-parent" branch.

As for the different configurations of plugins, most of what's in the Apache parent pom are in the `pluginManagement` section, and only specify the versions of the plugins. Our configuration is typically setting the behavior of the plugins.

**Comment by ctubbsii** [comment]
I've migrated the old `fluo-io-parent` to the new `fluo-parent` branch, so it preserves history from that, to get you started.

**Comment by Garvit244** [comment]
I will do changes in new branch of fluo-io-parent repo and will do changes in that branch.
As Keith pointed out that 

> We were planning on releasing the Fluo project pom to Sonatype because we have not transitioned that project to Apache yet
So, Is there a need to change the **distributionManagement** in new parent pom also or can we use apache distribution management. 
Because when we are using apache as parent pom it has its own distributionManagement name so if we again specify distributionManagement in new parent-pom file it will override apache
distributionManagement.

**Comment by keith-turner** [comment]
@ctubbsii are you thinking that we will release the pom in https://github.com/apache/incubator-fluo/commits/fluo-parent through Apache?  I guess that could be the first release we make as an incubator project.

**Comment by ctubbsii** [comment]
@keith-turner Yes.

**Comment by ctubbsii** [comment]
Now that the fluo-parent POM has been pushed to the fluo-parent branch, we can proceed updating the master branch to use it.
