### ISSUE TITLE
Ensure all dependencies are compatible with ASLv2

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#702]
@joshelser brought this up in #435

**Comment by keith-turner** [comment]
I will look into this.

**Comment by keith-turner** [comment]
I ran the following command to see what Fluo is importing.

```bash
find . -name "*.java" | xargs cat | grep 'import ' | grep -v 'import org.apache.fluo' | grep -v 'import static org.apache.fluo' | grep -v 'import java' | sed 's/import //' | sed 's/[.][A-Za-z0-9]*[;]//' | sort -u
```

I found the source code has the following dependencies.   I looked up the license for each dependency. ASF legal docs mention [multiple licenses](http://www.apache.org/legal/resolved.html#mutually-exclusive)

Direct Dependency | License
-------------------------|-----------
logback                   |  As of release 0.9.18, logback source code and binaries are dual-licensed under the EPL v1.0 and the LGPL 2.1, or more formally
jcommander           | ASLv2
codahale metrics    | ASLv2
guava                     | ASLv2
accumulo               | ASLv2
commons configuration | ASLv2
commons io                   | ASLv2
curator                           | ASLv2
hadoop                          | ASLv2
log4j                               | ASLv2
thrift                               | ASLv2
twill                                | ASLv2
zookeeper                     | ASLv2
easymock                      | ASLv2
junit                               | EPLv1
org.mpierce.metrics.reservoir.hdrhistogram | BSD 2-Clause
slf4j                               | MIT

**Comment by keith-turner** [comment]
Looking at Fluo Recipes imports, its currently has the following dependencies.

Direct Dependency   |  License
---------------------------|------------
kryo                           | New BSD License
guava                        | ASLv2
gson                          | ASLv2
accumulo                   | ASLv2
commons collections | ASLv2
commons lang           | ASLv2
commons io               | ASLv2
spark                         | ASLv2
junit                           | EPLv1
slf4j                           | MIT

**Comment by keith-turner** [comment]
#690 is related to this issue

**Comment by joshelser** [comment]
Wow, great work here @keith-turner!

> logback 	As of release 0.9.18, logback source code and binaries are dual-licensed under the EPL v1.0 and the LGPL 2.1, or more formally

This one would fall into the Category-B licenses which that page you linked describes. Essentially, as long as you are only bundling logback in binary form, you're fine. We may not copy logback source into Fluo.

The rest of these also look fine (BSD and MIT are compatible). It's also worth mentioning that if Fluo only creates a source release, we don't need to do anything else for the first release (L&N don't need anything additions). Only if Fluo also wants to ship some extra artifacts in addition to the required source release do we get into maintaining multiple versions of L&N. Remember that this also applies to jars that get deployed to nexus, not just a "binary tarball" like Accumulo does.

If you're content, so am I. We can check off the first item under "Verify distribution rights" on http://incubator.apache.org/projects/fluo.html too.

**Comment by keith-turner** [comment]
>  Only if Fluo also wants to ship some extra artifacts in addition to the required source release do we get into maintaining multiple versions of L&N.

As @ctubbsii  suggested in #690 we may end up with a binary tarball that only contains the Fluo jars and helper scripts for downloading other jars.   In that case we may not need to do anything with L&N.  That's not what we currently have though.  I am kinda leaning towards moving in that direction, it saves us work and makes it clear that dependency versions are really only recommendations.

**Comment by joshelser** [comment]
> we may end up with a binary tarball that only contains the Fluo jars and helper scripts for downloading other jars. In that case we may not need to do anything with L&N

Ok, as long as Fluo doesn't have any source code copied from other projects, I agree with you.

>  That's not what we currently have though. I am kinda leaning towards moving in that direction, it saves us work and makes it clear that dependency versions are really only recommendations. 

I will wait on marking off the checklist at least until we get a first release out. I'm all for knocking off these items, but I want to make sure that it's representative of what we actually release in the end.

Thanks again!

**Comment by keith-turner** [comment]
Now that #690 is done, I think this is done.  Anything else you would like to see done @joshelser?

**Comment by joshelser** [comment]
> Ok, as long as Fluo doesn't have any source code copied from other projects, I agree with you.

Can I get an ACK on this?

> Now that #690 is done, I think this is done.

I believe I would agree with you. Reserve all rights to change my mind when I see rc0 :)

**Comment by keith-turner** [comment]
> Can I get an ACK on this?

I don't know of any code copied from another project.

**Comment by joshelser** [comment]
>  >  Can I get an ACK on this?

> I don't know of any code copied from another project

Great. SGTM

**Comment by mikewalch** [comment]
Can this issue be closed?

**Comment by joshelser** [comment]
Fine by me.
