### ISSUE TITLE
Update documentation for 1.0.0 version number.

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#707]
Need to update Fluo's documentation for 1.0.0.   Like in some places the fluo 1.0.0-beta2 tar ball is mentioned.

**Comment by mikewalch** [comment]
I think the version in all of the poms should be changed from 1.0.0-beta-3-SNAPSHOT to 1.0.0-SNAPSHOT.

**Comment by ctubbsii** [comment]
Since the final release will be `1.0.0-incubating`, I wonder if there's going to be an issue with any version ranges... for example if `-incubating` sorts before, and is treated as "older" than `-SNAPSHOT` by maven.

**Comment by keith-turner** [comment]
> Since the final release will be 1.0.0-incubating, I wonder if there's going to be an issue with any version ranges... for example if -incubating sorts before, and is treated as "older" than -SNAPSHOT by maven.

Ooooppps, @ctubbsii I didn't see this comment before merging.  Just looked at the diffs and merged.   Do you think something needs to be done?

**Comment by mikewalch** [comment]
@keith-turner, there shouldn't be a problem.  @ctubbsii tested it yesterday and `-incubating` sorts after.
