### ISSUE TITLE
Use Charsequence in API

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#714]
In methods that currently take String as a parameter in the API package, it would be better to take Charsequence.  Since String can be assigned to Charsequence this will support all existing code, plus more like the assignment of StringBuffer etc.

For example we can change

```java
   Bytes.of(String s)
```

to 

```java
   Bytes.of(Charsequence s)
```

Methods that return String should not be changed.  The following is take from [a stackoverflow post](http://stackoverflow.com/questions/11323962/exact-difference-between-charsequence-and-string-in-java) and I think this makes sense.

> Any method which accepts a CharSequence can operate on all of these equally well. Any method which only accepts a String will require conversion. So using CharSequence as an argument type in all the places where you don't care about the internals is prudent. However you should use String as a return type if you actually return a String, because that avoids possible conversions of returned values if the calling method actually does require a String.

It would be ok for now to change the implementation to call `cs.toString().getBytes()` where `cs` is a CharSequence.  Once the API change is made, its easy to optimize the implementation in the future w/o impacting users.

**Comment by Garvit244** [comment]
will pick this one

**Comment by keith-turner** [comment]
@Garvit244 will you be able to work on this in the next week or two?  We are slowly moving towards a release of the parent pom, so there is no hurry at the moment. After the parent pom we can start working on the release of Fluo itself.

**Comment by Garvit244** [comment]
Sure.  Actually I m facing some problems with my laptop so won't able to work on this.  Will definitely try to complete this one by  this or next week.
