### ISSUE TITLE
Add append method for ByteBuilder that takes a byte array, length, and offset

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#715]
BytesBuilder has a method that takes a byte array, but not one that takes a part of a byte array.

**Comment by cjmctague** [comment]
Will start this

**Comment by cjmctague** [comment]
@keith-turner https://github.com/cjmctague/incubator-fluo/commit/82cb3b696e480cbb99ef6ec5d62ebe79e38f5aa4 

Am I understanding this correctly?

Do you just want a single byte from the array or do you want a section of bytes?

**Comment by keith-turner** [comment]
> Do you just want a single byte from the array or do you want a section of bytes?

A section of bytes.

**Comment by keith-turner** [comment]
Want behavior similar to the following method, except `byte[]` instead of `char[]`.

https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#append%28char[],%20int,%20int%29

**Comment by cjmctague** [comment]
Gotcha.

**Comment by cjmctague** [comment]
@keith-turner https://github.com/cjmctague/incubator-fluo/commit/1a1c7236d34a45e2640268097f28ad990b35f36b

More what you were looking for?

**Comment by keith-turner** [comment]
Yeah that looks good.   Maybe also add a unit test.  There is already a unit test for BytesBuilder, buts it in a different module.   Its in the core module in modules/core/src/test/java/.../BytesByulderTest.java

**Comment by cjmctague** [comment]
@keith-turner https://github.com/cjmctague/incubator-fluo/commit/662e9a6fa7651982166f69463debbc847e34c2ea

Pull request against master?

**Comment by keith-turner** [comment]
> Pull request against master?

Yeah, that would be good.

**Comment by keith-turner** [comment]
Work done in PR #726
