### ISSUE TITLE
org.apache.fluo.integration.impl.StochasticBankIT should not print to console

### ISSUE THREAD

**Issue by ctubbsii** [apache/incubator-fluo#727]
Tests should not print to the console. They should use the logger, so that the output can be filtered with test logging configuration. Alternatively, they should write to an output file.

This particular test is pretty spammy during the build.

**Comment by ctubbsii** [comment]
This can also be addressed by making all test output redirect to a file.

**Comment by keith-turner** [comment]
I think changing that test to log.debug would be fine

**Comment by mikewalch** [comment]
I am working on this
