### ISSUE TITLE
Use Java hashcode helper methods in data classes

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#740]
Fluo could use `Arrays.hashCode`, `Objects.hash()`, etc in the implementation of its data class hashCode methods.  For example `Bytes.hashCode()` could be implemented with a call to `Arrays.hashCode()`.  Also `Column.hashCode()` could use `Objects.hash()`.

**Comment by cjmctague** [comment]
Will work on.

**Comment by cjmctague** [comment]
@keith-turner The hash shouldn't be changing from what is expected in the Tests right?

**Comment by keith-turner** [comment]
Which test?

**Comment by cjmctague** [comment]
` RowColumnTest.testBasic:53 expected:<4007699> but was:<4008691>`

**Comment by keith-turner** [comment]
its ok to change that in the test

**Comment by cjmctague** [comment]
@keith-turner I pushed it to my fork. Can you look over it
https://github.com/cjmctague/incubator-fluo/commit/a2d3e1d66f7acd83f47a7023d987e030b3a13b1b

**Comment by keith-turner** [comment]
I took a look at it.  The implementation of Bytes.hashCode() seems incorrect.  Seems like it would only hash one byte effectively?  I was thinking we could call Arrays.hashCode() on the byte array, but I see that the array is not available.  This got me thinking about moving all of the implementation of MutableBytes in Bytes and removing MutableBytes.  Also I realized that #743 needed to be done.  For now, you could drop the hashCode method from Bytes and introduce it in MutableBytes (using Arrays.hashCode).
