### ISSUE TITLE
Return type does not match parameter type for get(Collection<RowColumn>)

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#758]
The following method was added in #626.  

```java
interface Snapshot {
  Map<Bytes, Map<Column, Bytes>> get(Collection<RowColumn>);
}
```

Recently I was trying to use it with the Fluo tour and found the mismatch between input and output types annoying.  I think the following would be better.

```java
interface Snapshot {
  Map<RowColumn, Bytes> get(Collection<RowColumn>);
}
```

**Comment by ITSKATYMABYBABY** [comment]
I AM THE 183 CONTRIBUTIONS IN.&.OF LAST YEAR, NO DISRESPECT SIR. SINCERELY,

.KATELYN.MABY.BURSON.
