### ISSUE TITLE
CollisionIT failed

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#762]
While building PR #761 the following failure was seen by TravisCI.  I was able to run mvn verify 3 times locally w/o issue, so I don't think that PR is causing the change.  Need to further investigate why this test failed.

```
Running org.apache.fluo.integration.impl.CollisionIT

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 35.071 sec <<< FAILURE! - in org.apache.fluo.integration.impl.CollisionIT

testLotsOfCollisions(org.apache.fluo.integration.impl.CollisionIT)  Time elapsed: 35.055 sec  <<< FAILURE!

java.lang.AssertionError: Duplicate row col 4:stat:total:2000000000000000

	at org.apache.fluo.integration.impl.CollisionIT.testLotsOfCollisions(CollisionIT.java:170)
```

**Comment by ctubbsii** [comment]
I saw:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.547 sec <<< FAILURE! - in org.apache.fluo.integration.impl.CollisionIT
testLotsOfCollisions(org.apache.fluo.integration.impl.CollisionIT)  Time elapsed: 17.545 sec  <<< FAILURE!
java.lang.AssertionError: Duplicate row col all:stat:total:2000000000000000
	at org.apache.fluo.integration.impl.CollisionIT.testLotsOfCollisions(CollisionIT.java:170)
```

Same problem. Different row.

**Comment by ctubbsii** [comment]
So, this was just a test bug, not a problem with collisions? That's a relief.

**Comment by keith-turner** [comment]
> So, this was just a test bug, not a problem with collisions? That's a relief.

I don't have positive confirmation of that.  Looking at the code I could see that the logic for waiting was wrong, so maybe sometimes the test did not wait long enough.

In the place where the test failed it was attempting to verify the Fluo GC iterator worked correctly.  So if there is a problem, its with garbage collection not cleaning up everything it should.  The earlier part of the test that checks transactions worked correctly w/ collisions did not fail.
