### ISSUE TITLE
Add copyTo() method to bytes

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#827]
For data serialization use cases, a user may want to copy multiple Bytes objects to a byte array.   The current options for that are to call Bytes.toArray() or use the Bytes.byteAt() method.  If Bytes had a `copyTo(byte[] dest, int offset)`   method then it could support this use case more efficiently.  The following is an example.

```java
Bytes field1 = Bytes.of("foo");
Bytes field2 = Bytes.of("bar");

byte[] dest = new byte[field1.length() + field2.lenght() + 1];

field1.copyTo(dest, 0);
dest[field1.lenght()] = ':';
field2.copyTo(dest, field1.lenght()+1);
```

**Comment by ctubbsii** [comment]
Looking at this example, I'm wondering if the javadoc for any such method should make it a point to remind the user that the offset and length correspond to the UTF-8 encoded byte array form of any String/CharSequence that they may have used to construct the Bytes with, and may differ from the character offsets in the original string.

**Comment by keith-turner** [comment]
For the case where a subsequence of a Bytes object needs to be copied, I was thinking the `subsequence()` method could be used.  For example the following could copy the 1st 255 bytes of `b1` to `dest` starting at offset 1024.

```java 

byte[] dest = ...

Bytes b1;

b1.subsequence(0,255).copyTo(dest, 1024);
```

However, calling subsequence will allocate an intermediate Bytes object.  To avoid this, we could have a method like `copyTo(int sourceOffset,  byte[] dest, int destOffset, int len)` instead of `copyTo(byte[] dest, int offset)`.

**Comment by mjwall** [comment]
I can take a swing at this one.  Is there a way for us to assign issues in GH?

**Comment by keith-turner** [comment]
Not yet, but hopefully soon [INFRA-14121](https://issues.apache.org/jira/browse/INFRA-14121)
