### ISSUE TITLE
Optimize ByteArrayUtil.concat()

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#830]
`static byte[] ByteArrayUtil.concat(Bytes ... listOfBytes)` has the following performance problems

 * It uses ByteArrayOutputStream() which has synchronized public methods.  This only used by a single thread and in the past I have observed this unnecessary synchronization can have significant consequences.
 * It takes var args, however the most frequent use of it passes two arguments.  This results in the allocation of a `new Bytes[2]` which could easily be avoided with a  two argument version of the method.

Optimizing this could possible use `copyTo()` from #827 and directly creating a byte array.  The only tricky part is the `writeVInt()` method.  One possible workaround would be to not use `writeVInt()` when the length is less than or equal to 127.  When it is longer, then use ByteArrayOutputStream() but set the array.

**Comment by keith-turner** [comment]
Accumulo just avoid the output stream altogether.

https://github.com/apache/accumulo/blob/master/core/src/main/java/org/apache/accumulo/core/util/UnsynchronizedBuffer.java

**Comment by mjwall** [comment]
I'd like to try this one too unless someone else is working on it

**Comment by cjmctague** [comment]
@keith-turner Could we utilize the `UnsynchronizedBuffer` class in fluo? It would eliminate the problems here. I used it and got it to work for this applications but you know we can't import non-public classes.

**Comment by keith-turner** [comment]
> Could we utilize the UnsynchronizedBuffer class in fluo?

We could copy it.  Since its not part of Accumulo public API, would not want to use it from Accumulo.

**Comment by keith-turner** [comment]
@cjmctague I just looked that Accumuo class.  We don't need to copy the entire thing.  We could just copy and modify what we need.  Could possibly create two methods.  A method tells how many bytes an integer will use `int vLen(int i)` and a method writes a vint directly to a byte array `void writeVint(byte[] dest, int offset, int i)`.
