### ISSUE TITLE
Add a quick profile to pom  that disables sanity checks

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#857]
I often find myself doing thing like the following to quickly run some maven action.

```
mvn clean install -DskipTests -Dfindbugs.skip -Dcheckstyle.skip -Drat.skip
```

I think it would be nice to add a profile to maven that disables all of these things.  Maybe something like the following.

```
mvn -Pquick clean install
```

**Comment by ctubbsii** [comment]
I would not recommend doing this at the project level. It can encourage bad behavior among people who don't understand the implications of these flags. It's probably better to create per-user profiles in your `~/.m2/settings.xml` file based on your individual needs/preferences, which an understanding of what these do, than to do it for all developers on the project.

**Comment by keith-turner** [comment]
> I would not recommend doing this at the project level. It can encourage bad behavior among people who don't understand the implications of these flags. 

All tools can potentially be misused, but I don't think that is a good argument for not making a tool.  The profile would be off by default.  So it would be up to someone to make a choice to use it.

>  It's probably better to create per-user profiles in your ~/.m2/settings.xml file based on your individual needs/preferences, which an understanding of what these do, than to do it for all developers on the project.

That's a good idea, but it would be nice to share.  Also, the settings may differ between versions of Fluo.  Putting it in the project pom allows devs to share and easily obtain the benefits when others add a new plugin and update the profile.  

I added the following to my `~/.m2/settings.xml` and it works nicely.

```xml
   <profile>
    <id>quick</id>
    <properties>
      <skipTests>true</skipTests>
      <rat.skip>true</rat.skip>
      <findbugs.skip>true</findbugs.skip>
      <checkstyle.skip>true</checkstyle.skip>
      <modernizer.skip>true</modernizer.skip>
    </properties>
   </profile>
```

Running `mvn clean install -Pquick` takes 17 seconds.  Running `mvn clean install -DskipTests` takes 52 seconds.

**Comment by ctubbsii** [comment]
> All tools can potentially be misused, but I don't think that is a good argument for not making a tool. The profile would be off by default. So it would be up to someone to make a choice to use it.

My argument isn't that it *could be* misused. My argument is that it *encourages* misuse. Off by default helps, but relying on users to set their own flags, based on an understanding of what they are actually trying to accomplish, is better.

The above profile, if baked in to the project POM and documentation, encourages people to use `-Pquick` without any understanding at all about what checks are disabled or why it is okay to do disable them. At the very least, naming the profile something like "skip-quality-checks" or something hints at what is being lost.

> Also, the settings may differ between versions of Fluo. Putting it in the project pom allows devs to share and easily obtain the benefits when others add a new plugin and update the profile.

Automatically benefiting from differences between versions seems like a mutually exclusive goal with understanding the implications of disabling these checks.

---

If the profile is off by default, and has a name which reflects what is lost/disabled, and has an XML comment in the POM explaining when/why it might be okay to use the profile (e.g. not in Jenkins, not in releases, etc.), I won't object strongly. But, I still think it's a bad idea, in general.

**Comment by keith-turner** [comment]
> My argument is that it encourages misuse.

I can't agree with this argument for its non-existence.  The main reason I can think it should not exist is that it adds to the effort required to understanding the pom, which is a maintenance burden.  I think this is a very small burden for this change, however lots of additions like these would make understanding the pom burdensome.  If no one else is interested in this change I will not add it, because its not worth polluting the pom if only one developer will use it.

> naming the profile something like "skip-quality-checks"

I am also in favor of a good name and good comments in the pom.  I think `skipQA` would be a nice short name.

**Comment by ctubbsii** [comment]
+1 for `skipQA` as the name, if you end up deciding to add this later.

**Comment by mikewalch** [comment]
+1, I like the idea of the profile. `skipQA` would be better name.
