### ISSUE TITLE
Create RC script creates email with wrong commit

### ISSUE THREAD

**Issue by keith-turner** [apache/incubator-fluo#866]
I just used the `create-release-candidate.sh` script to generate the email for 1.1.0 RC1.  The script generated an email with wrong commit.  It used the 1st commit on the RC branch, when it should have used the second commit.

**Comment by keith-turner** [comment]
Actually I think I created the RC branch incorrectly

**Comment by ctubbsii** [comment]
In case anyone looks at this in the future, the RC branch should be the first commit made by `release:prepare`. The second commit is the bump to the next snapshot version, which will be the version in the resulting maintenance branch (if there is one) after the release.
